// examples/test-completion.vue
<template>
  <div class="container">
    <h1>{{ title }}</h1>
    <button @click="handleClick">点击我</button>
    <!-- 在这里测试补全 -->
    <p>{{ user. }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

// 测试 Vue 文件中的代码补全
const title = ref('Hello Vue!')
const user = ref({
  name: 'John',
  email: 'john@example.com'
})

// 在这里输入点号应该触发补全
console.

// 测试对象属性访问
user.value.

// 测试函数调用补全
const handleClick = () => {
  // 测试补全
  user.value.
}

// 测试计算属性
const displayName = computed(() => {
  return user.value.
})
</script>

<style scoped>
.container {
  /* 测试 CSS 补全 */
  display: 
  background-color: 
  border-radius: 
}
</style>

// examples/test-completion.tsx
import React from 'react';

// 测试 TSX 文件中的代码补全
interface Props {
    name: string;
    age: number;
}

const TestComponent: React.FC<Props> = ({ name, age }) => {
    // 在这里输入点号应该触发补全
    console.log('test');
    
    // 测试对象属性访问
    const user = { name: 'test', email: 'test@example.com' };
    user.name;
    
    // 测试 React 相关补全
    const [state, setState] = React.useState('');
    setState('new value');
    
    const handleClick = () => {
        console.log('clicked');
    };
    
    return (
        <div>
            <h1>{name}</h1>
            <p>Age: {age}</p>
            {/* 测试 JSX 中的补全 */}
            <button onClick={handleClick}>Click me</button>
        </div>
    );
};

export default TestComponent;
